name: PR Verifier

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions: read-all

jobs:
  verify:
    name: verify PR contents
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: read
    steps:
      - name: PR verification
        run: echo "PR verification passed"
